### ISSUE TITLE
Migration with Elixir v1.16.0/OTP26 causes warnings on migration

### ISSUE THREAD

**Issue by sekiyama58** [gumi/yacto#24]
Running migration with Elixir v1.16.0 and OTP 26.2.1 causes following warning for each table:
```
warning: negative steps are not supported in String.slice/2, pass 0..-5//1 instead
  (elixir 1.16.0) lib/string.ex:2368: String.slice/2
  (yacto 2.0.5) lib/yacto/migration/file.ex:177: Yacto.Migration.File.path_to_structure/2
  (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
  (yacto 2.0.5) lib/yacto/migration/file.ex:38: Yacto.Migration.File.list_migration_files/2
```
at:
https://github.com/gumi/yacto/blob/dfd842f9a3bacc8cabf7231314adefa67671a5f6/lib/yacto/migration/file.ex#L177

**Comment by melpon** [comment]
報告ありがとうございます。修正して 2.0.6 をリリースしました。 https://hex.pm/packages/yacto/2.0.6
