### ISSUE TITLE
map.field notation deprecation warning on migration with Elixir 1.17

### ISSUE THREAD

**Issue by sekiyama58** [gumi/yacto#25]
In Elixir 1.17.x, I see the following deprecation warning each time I run migrations.

```
warning: using map.field notation (without parentheses) to invoke function DB.Repo.__adapter__() is deprecated, you must add parentheses instead: remote.function()
  (yacto 2.1.0) lib/yacto/migration/schema_migration.ex:17: Yacto.Migration.SchemaMigration.ensure_schema_migrations_table!/1
  (yacto 2.1.0) lib/yacto/migration/migrator.ex:7: anonymous fn/3 in Yacto.Migration.Migrator.migrated_versions/3
  (yacto 2.1.0) lib/yacto/migration/migrator.ex:153: Yacto.Migration.Migrator.verbose_schema_migration/3
```

**Comment by melpon** [comment]
https://github.com/gumi/yacto/commit/58769218c6ff03d07be7ea4bcdf5ffff48f88aa9 で対応しました。
